/**
 * Shared Tamil/English label map + small helpers for the Mass Intention
 * receipt (receiptPdf.js), bulk receipt (bulkReceiptPdf.js), and Daily
 * Prayer Register (dailyRegisterPdf.js) -- the three printouts that support
 * a `lang` param. Kept in one place so the three generators can't drift out
 * of sync on wording, and so adding a fourth language later only means
 * adding one more object below rather than touching three files.
 *
 * This is deliberately separate from the frontend's en.ts/ta.ts -- those
 * translate the app's UI chrome (buttons, form labels), not print output,
 * and pulling them in here would mean the backend depending on frontend
 * source. A handful of fixed print labels duplicated here is simpler and
 * more robust than trying to share one file across the two apps.
 */

const LABELS = {
  en: {
    receiptTitle: 'MASS INTENTION RECEIPT',
    bulkReceiptTitle: 'MASS INTENTIONS RECEIPT',
    registerTitle: 'DAILY REGISTER',
    registerNamesOnlyTitle: 'DAILY REGISTER -- NAMES & INTENTIONS',
    registerReasonsOnlyTitle: 'DAILY REGISTER -- MASS INTENTIONS ONLY',
    intentions: 'Intentions',
    billedBy: 'Billed By',
    generatedBy: 'Generated by',
    receiptNo: 'Receipt No.',
    // The single Mass Intention receipt's own label for created_at, right
    // next to Receipt No. -- distinct from `enteredDate` (same underlying
    // column) used by the Daily Register/Collections reports, so renaming
    // it here doesn't relabel those.
    billedDate: 'Billed Date',
    bookedBy: 'Booked By',
    date: 'Date',
    mass: 'Mass',
    // Used wherever a printout shows the Mass's own date specifically --
    // the single receipt (receiptPdf.js/receiptHtml.js) and the Bulk Mass
    // Intention receipt's table header (bulkReceiptPdf.js) -- so it can't be
    // confused with `enteredDate` (when the booking was made) or with the
    // generic `date` key other printouts (Collections reports, Daily
    // Register) use for their own, differently-scoped date fields.
    massDate: 'Mass Date',
    massTime: 'Mass Time',
    offeredFor: 'Offered for',
    massIntention: 'Mass Intention',
    offering: 'Offering',
    offeringDescription: 'Offering Description',
    totalOffering: 'Total Offering',
    name: 'Name',
    amount: 'Amount',
    phone: 'Phone',
    paymentMethod: 'Payment Method',
    reference: 'Reference',
    page: 'Page',
    of: 'of',
    generated: 'Generated',
    scanCalendar: 'Scan to add this Mass to your calendar',
    scanVerify: 'Scan to verify receipt',
    defaultThankYou: 'Thank you for your offering. God Bless You.',
    noRecords: 'No mass intentions were recorded for this date.',
    churchOffice: 'Church Office',
    system: 'System',
    // Contribution receipt (contributionReceiptPdf.js) -- its own title/
    // donor/type/thank-you wording; everything else on it (billedBy,
    // receiptNo, date, amount, generated, churchOffice, system) is shared
    // with the Mass Intention receipt above.
    contributionReceiptTitle: 'CONTRIBUTION RECEIPT',
    donor: 'Donor',
    contributionType: 'Contribution Type',
    contributionThankYou: 'Thank you for your generous contribution. God Bless You.',
    // Footer note shown on the single Mass Intention and Contribution
    // receipts (receiptPdf.js/receiptHtml.js, contributionReceiptPdf.js/
    // contributionReceiptHtml.js) -- fixed A5 page, content-sized footer,
    // see receiptPdf.js's own comment on why the page itself can't just
    // shrink to fit.
    retainReceipt: 'Please retain this receipt for your records.',
    visitUsAt: 'Visit us at',
    // Collections/Contributions detail reports (collectionsDetailPdf.js/
    // contributionCollectionsDetailPdf.js) -- these used to be English-only
    // by design (an admin oversight report); now support the same `lang`
    // as every other printout.
    method: 'Method',
    notSpecified: 'Not specified',
    collectionsBreakdownMine: 'MY COLLECTIONS BREAKDOWN',
    collectionsBreakdownAll: 'COLLECTIONS BREAKDOWN (ALL USERS)',
    contributionsBreakdownMine: 'MY CONTRIBUTIONS BREAKDOWN',
    contributionsBreakdownAll: 'CONTRIBUTIONS BREAKDOWN (ALL USERS)',
    printedBy: 'Printed By',
    enteredDate: 'Entered Date',
    period: 'Period',
    noCollectionsPeriod: 'No collections were recorded for this period.',
    noContributionsPeriod: 'No contributions were recorded for this period.',
    total: 'Total',
    massIntentionsReportTitle: 'MASS INTENTIONS REPORT',
    certificatesReportTitle: 'CERTIFICATES REPORT',
    certificateType: 'Certificate Type',
    baptism: 'Baptism',
    marriage: 'Marriage',
    death: 'Death',
    noMassIntentionsPeriod: 'No mass intentions recorded for this period.',
    noCertificatesPeriod: 'No certificates recorded for this period.',
    methodCash: 'Cash',
    methodUpi: 'UPI',
    methodCard: 'Card',
    methodCheque: 'Cheque',
    methodBankTransfer: 'Bank Transfer',
    methodOther: 'Other',
  },
  ta: {
    receiptTitle: 'திருப்பலி கருத்து ரசீது',
    bulkReceiptTitle: 'திருப்பலி கருத்துகள் ரசீது',
    registerTitle: 'தினசரி ஜெப பதிவேடு',
    registerNamesOnlyTitle: 'தினசரி ஜெப பதிவேடு -- பெயர்கள் & கருத்துகள்',
    registerReasonsOnlyTitle: 'தினசரி ஜெப பதிவேடு -- திருப்பலி கருத்துக்கள் மட்டும்',
    intentions: 'கருத்துக்கள்',
    billedBy: 'பில் செய்தவர்',
    generatedBy: 'உருவாக்கியவர்',
    receiptNo: 'ரசீது எண்.',
    billedDate: 'பில் தேதி',
    bookedBy: 'பதிவு செய்தவர்',
    date: 'தேதி',
    mass: 'திருப்பலி',
    massDate: 'திருப்பலி தேதி',
    massTime: 'திருப்பலி நேரம்',
    offeredFor: 'யாருக்காக',
    massIntention: 'திருப்பலி கருத்து',
    offering: 'காணிக்கை',
    offeringDescription: 'காணிக்கை விவரம்',
    totalOffering: 'மொத்த காணிக்கை',
    name: 'பெயர்',
    amount: 'தொகை',
    phone: 'தொலைபேசி',
    paymentMethod: 'கட்டண முறை',
    reference: 'குறிப்பு எண்',
    page: 'பக்கம்',
    of: '/',
    generated: 'உருவாக்கப்பட்டது',
    scanCalendar: 'இந்த திருப்பலியை உங்கள் நாட்காட்டியில் சேர்க்க ஸ்கேன் செய்யவும்',
    scanVerify: 'ரசீதை சரிபார்க்க ஸ்கேன் செய்யவும்',
    defaultThankYou: 'உங்கள் காணிக்கைக்கு நன்றி. இறைவன் ஆசீர்வதிப்பாராக.',
    noRecords: 'இந்த தேதிக்கு திருப்பலி கருத்துகள் எதுவும் பதிவு செய்யப்படவில்லை.',
    churchOffice: 'தேவாலய அலுவலகம்',
    system: 'கணினி',
    contributionReceiptTitle: 'பங்களிப்பு ரசீது',
    donor: 'நன்கொடையாளர்',
    contributionType: 'பங்களிப்பு வகை',
    contributionThankYou: 'உங்கள் தாராள பங்களிப்புக்கு நன்றி. இறைவன் ஆசீர்வதிப்பாராக.',
    retainReceipt: 'இந்த ரசீதை உங்கள் பதிவுகளுக்காக பாதுகாத்து வைக்கவும்.',
    visitUsAt: 'எங்களை பார்வையிடவும்',
    method: 'முறை',
    notSpecified: 'குறிப்பிடப்படவில்லை',
    collectionsBreakdownMine: 'எனது வசூல் விவரம்',
    collectionsBreakdownAll: 'வசூல் விவரம் (அனைத்து பயனர்களும்)',
    contributionsBreakdownMine: 'எனது பங்களிப்பு விவரம்',
    contributionsBreakdownAll: 'பங்களிப்பு விவரம் (அனைத்து பயனர்களும்)',
    massIntentionsReportTitle: 'திருப்பலி கருத்துகள் அறிக்கை',
    certificatesReportTitle: 'சான்றிதழ்கள் அறிக்கை',
    certificateType: 'சான்றிதழ் வகை',
    baptism: 'ஞானஸ்நானம்',
    marriage: 'திருமணம்',
    death: 'இறப்பு',
    noMassIntentionsPeriod: 'இந்த காலகட்டத்தில் எந்த திருப்பலி கருத்தும் பதிவு செய்யப்படவில்லை.',
    noCertificatesPeriod: 'இந்த காலகட்டத்தில் எந்த சான்றிதழும் பதிவு செய்யப்படவில்லை.',
    printedBy: 'அச்சிட்டவர்',
    enteredDate: 'பதிவு செய்த தேதி',
    period: 'காலம்',
    noCollectionsPeriod: 'இந்த காலகட்டத்தில் எந்த வசூலும் பதிவு செய்யப்படவில்லை.',
    noContributionsPeriod: 'இந்த காலகட்டத்தில் எந்த பங்களிப்பும் பதிவு செய்யப்படவில்லை.',
    total: 'மொத்தம்',
    methodCash: 'பணம்',
    methodUpi: 'UPI',
    methodCard: 'கார்டு',
    methodCheque: 'காசோலை',
    methodBankTransfer: 'வங்கி பரிமாற்றம்',
    methodOther: 'மற்றவை',
  },
  hi: {
    receiptTitle: 'मिस्सा प्रार्थना रसीद',
    bulkReceiptTitle: 'मिस्सा प्रार्थनाएं रसीद',
    registerTitle: 'दैनिक प्रार्थना रजिस्टर',
    registerNamesOnlyTitle: 'दैनिक प्रार्थना रजिस्टर -- केवल नाम व आशय',
    registerReasonsOnlyTitle: 'दैनिक प्रार्थना रजिस्टर -- केवल प्रार्थना आशय',
    intentions: 'प्रार्थनाएं',
    billedBy: 'बिल किया गया',
    generatedBy: 'द्वारा उत्पन्न',
    receiptNo: 'रसीद सं.',
    billedDate: 'बिल तिथि',
    bookedBy: 'द्वारा बुक',
    date: 'तारीख',
    mass: 'मिस्सा',
    massDate: 'मिस्सा तिथि',
    massTime: 'मिस्सा समय',
    offeredFor: 'के लिए समर्पित',
    massIntention: 'मिस्सा प्रार्थना आशय',
    offering: 'चढ़ावा',
    offeringDescription: 'चढ़ावा विवरण',
    totalOffering: 'कुल चढ़ावा',
    name: 'नाम',
    amount: 'राशि',
    phone: 'फ़ोन',
    paymentMethod: 'भुगतान विधि',
    reference: 'संदर्भ सं.',
    page: 'पृष्ठ',
    of: 'का',
    generated: 'उत्पन्न',
    scanCalendar: 'कैलेंडर में जोड़ने के लिए स्कैन करें',
    scanVerify: 'रसीद सत्यापन के लिए स्कैन करें',
    defaultThankYou: 'आपके चढ़ावे के लिए धन्यवाद। ईश्वर आपको आशीर्वाद दें।',
    noRecords: 'इस तिथि के लिए कोई मिस्सा प्रार्थना दर्ज नहीं है।',
    churchOffice: 'चर्च कार्यालय',
    system: 'सिस्टम',
    contributionReceiptTitle: 'दान व अंशदान रसीद',
    donor: 'दानकर्ता',
    contributionType: 'अंशदान प्रकार',
    contributionThankYou: 'आपके उदार योगदान के लिए धन्यवाद। ईश्वर आपको आशीर्वाद दें।',
    retainReceipt: 'कृपया इस रसीद को अपने रिकॉर्ड के लिए सुरक्षित रखें।',
    visitUsAt: 'वेबसाइट',
    method: 'विधि',
    notSpecified: 'अनिर्दिष्ट',
    collectionsBreakdownMine: 'मेरा संग्रह विवरण',
    collectionsBreakdownAll: 'कुल संग्रह विवरण (सभी उपयोगकर्ता)',
    contributionsBreakdownMine: 'मेरा अंशदान विवरण',
    contributionsBreakdownAll: 'कुल अंशदान विवरण (सभी उपयोगकर्ता)',
    massIntentionsReportTitle: 'मिस्सा प्रार्थना रिपोर्ट',
    certificatesReportTitle: 'प्रमाणपत्र रिपोर्ट',
    certificateType: 'प्रमाणपत्र प्रकार',
    baptism: 'बपतिस्मा',
    marriage: 'विवाह',
    death: 'मृत्यु',
    noMassIntentionsPeriod: 'इस अवधि में कोई मिस्सा प्रार्थना दर्ज नहीं है।',
    noCertificatesPeriod: 'इस अवधि में कोई प्रमाणपत्र दर्ज नहीं है।',
    printedBy: 'द्वारा प्रिंट',
    enteredDate: 'प्रविष्टि तिथि',
    period: 'अवधि',
    noCollectionsPeriod: 'इस अवधि में कोई संग्रह नहीं है।',
    noContributionsPeriod: 'इस अवधि में कोई योगदान नहीं है।',
    total: 'कुल',
    methodCash: 'नकद',
    methodUpi: 'UPI',
    methodCard: 'कार्ड',
    methodCheque: 'चेक',
    methodBankTransfer: 'बैंक ट्रांसफर',
    methodOther: 'अन्य',
  },
};

/** Looks up one label, falling back to English for an unrecognized lang
 * (mirrors every other `lang`-handling spot in this app -- see
 * LanguageService.readStored() on the frontend). */
function t(lang, key) {
  return (LABELS[lang] || LABELS.en)[key] || LABELS.en[key] || key;
}

const TAMIL_RANGE = /[஀-௿]/;

/** True if any of the given values contain Tamil-script characters.
 * Booked By / name / custom intention are free text -- office staff can
 * type a Tamil name or intention regardless of which language the report
 * itself is being printed in (see LanguageService's "en"/"ta" toggle,
 * which only controls the fixed labels above, not what staff typed into
 * those fields) -- so font selection can't rely on `lang` alone. */
function hasTamilText(...values) {
  return values.some((v) => typeof v === 'string' && TAMIL_RANGE.test(v));
}

/** Which registered pdfPrinter.js font family a document should use --
 * Roboto has no Tamil glyphs at all, see pdfPrinter.js's NotoSansTamil
 * entry. Picked when the report's own language is Tamil OR any of the
 * actual free-text content being printed contains Tamil (see
 * hasTamilText above) -- NotoSansTamil covers Latin too, so it's safe to
 * use for a document that's otherwise all English. */
function fontFor(lang, ...contentValues) {
  return lang === 'ta' || hasTamilText(...contentValues) ? 'NotoSansTamil' : 'Roboto';
}

/** Same fallback rule as the frontend's localized-name.util.ts -- Tamil
 * name when requested and set, else the English name. Used for both Mass
 * Intention preset text (name/name_ta) and Mass names (mass_name/
 * mass_name_ta) coming off massIntentionRepository's BASE_SELECT. */
function localizedName(name, nameTa, lang) {
  if (lang === 'ta' && nameTa) return nameTa;
  return name;
}

/** The church address line shown under its name on printed receipts (see
 * receiptPdf.js/contributionReceiptPdf.js) -- `address_ta` is one free-text
 * override for the whole line (see migration 032's own comment for why it's
 * not per-field address_line1_ta/city_ta columns), used whenever `lang` is
 * Tamil and it's actually been filled in; otherwise the usual English
 * "address_line1, city" combo. */
function addressLine(church, lang) {
  if (lang === 'ta' && church?.address_ta) return church.address_ta;
  return [church?.address_line1, church?.city].filter(Boolean).join(', ');
}

const METHOD_KEYS = {
  cash: 'methodCash',
  upi: 'methodUpi',
  card: 'methodCard',
  cheque: 'methodCheque',
  bank_transfer: 'methodBankTransfer',
  other: 'methodOther',
};

/** A payment method code (payment_transactions.method, e.g. 'bank_transfer')
 * as display text -- translated for the known fixed set (see
 * paymentService.js's VALID_METHODS), title-cased as a fallback for
 * anything else so an unrecognized/future code still reads reasonably
 * rather than showing a raw key. */
function paymentMethodLabel(method, lang) {
  if (!method) return t(lang, 'notSpecified');
  const key = METHOD_KEYS[method.toLowerCase()];
  if (key) return t(lang, key);
  return method.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

/** "Period: 01-08-2026 to 31-08-2026" -- Tamil phrases a date range as
 * "X முதல் Y வரை" (from X to Y), which surrounds both dates rather than
 * joining them with a single translatable word the way English's "to"
 * does, so this builds the whole phrase per language instead of
 * word-substituting through `t`. Used by collectionsDetailPdf.js/
 * contributionCollectionsDetailPdf.js's multi-day header line. */
function periodText(lang, fromText, toText) {
  return lang === 'ta' ? `${t(lang, 'period')}: ${fromText} முதல் ${toText} வரை` : `${t(lang, 'period')}: ${fromText} to ${toText}`;
}

module.exports = { t, fontFor, localizedName, hasTamilText, addressLine, paymentMethodLabel, periodText };
