'use strict';

/**
 * Column headings used by Excel export, the import template and the header
 * matching in import. Keyed by the SAME i18n keys the Angular UI uses
 * (frontend/src/app/core/i18n/en.ts / ta.ts) and holding the exact same
 * English and Tamil text, so a sheet heading is always what the user sees on
 * the form or list. When a label changes in the UI, change it here too --
 * labels.test.js checks this table against the two translation files.
 */
const LABELS = {
  "certificates.common.certificateNo": { en: "Certificate No.", ta: "சான்றிதழ் எண்." },
  "certificates.common.gender": { en: "Gender", ta: "பாலினம்" },
  "certificates.common.priest": { en: "Priest", ta: "குரு" },
  "certificates.common.priestCustom": { en: "Priest Name (if not in list above)", ta: "குரு பெயர் (பட்டியலில் இல்லையெனில்)" },
  "certificates.common.remarks": { en: "Remarks", ta: "குறிப்புகள்" },
  "certificates.baptism.colDateOfBirth": { en: "Date of Birth", ta: "பிறந்த தேதி" },
  "certificates.baptism.colDateOfBaptism": { en: "Date of Baptism", ta: "ஞானஸ்நான தேதி" },
  "certificates.baptism.fieldChildName": { en: "Child's Christian Name", ta: "குழந்தையின் கிறிஸ்தவ பெயர்" },
  "certificates.baptism.fieldSex": { en: "Sex", ta: "பாலினம்" },
  "certificates.baptism.fieldPlaceOfBaptism": { en: "Place of Baptism", ta: "ஞானஸ்நான இடம்" },
  "certificates.baptism.fieldFatherName": { en: "Father's Name", ta: "தந்தையின் பெயர்" },
  "certificates.baptism.fieldMotherName": { en: "Mother's Name", ta: "தாயின் பெயர்" },
  "certificates.baptism.fieldParentResidence": { en: "Parent's Residence", ta: "பெற்றோர் வசிப்பிடம்" },
  "certificates.baptism.fieldGodfather": { en: "Godfather", ta: "குருதந்தை" },
  "certificates.baptism.fieldGodmother": { en: "Godmother", ta: "குருதாய்" },
  "certificates.baptism.fieldPriestWhoBaptised": { en: "Priest who Baptised", ta: "ஞானஸ்நானம் அளித்த குரு" },
  "certificates.marriage.colMarriageDate": { en: "Marriage Date", ta: "திருமண தேதி" },
  "certificates.marriage.fieldWhenMarried": { en: "When Married", ta: "திருமணமான தேதி" },
  "certificates.marriage.fieldWhereMarried": { en: "Where Married", ta: "திருமணம் நடந்த இடம்" },
  "certificates.marriage.fieldGroomName": { en: "Name of the Bridegroom", ta: "மணமகனின் பெயர்" },
  "certificates.marriage.fieldBrideName": { en: "Name of the Bride", ta: "மணமகளின் பெயர்" },
  "certificates.marriage.fieldGroomAge": { en: "Age (Bridegroom)", ta: "வயது (மணமகன்)" },
  "certificates.marriage.fieldBrideAge": { en: "Age (Bride)", ta: "வயது (மணமகள்)" },
  "certificates.marriage.fieldGroomCondition": { en: "Condition (Bridegroom)", ta: "நிலை (மணமகன்)" },
  "certificates.marriage.fieldBrideCondition": { en: "Condition (Bride)", ta: "நிலை (மணமகள்)" },
  "certificates.marriage.fieldGroomProfession": { en: "Profession (Bridegroom)", ta: "தொழில் (மணமகன்)" },
  "certificates.marriage.fieldBrideProfession": { en: "Profession (Bride)", ta: "தொழில் (மணமகள்)" },
  "certificates.marriage.fieldGroomResidence": { en: "Residence at Marriage (Bridegroom)", ta: "திருமணத்தின் போது வசிப்பிடம் (மணமகன்)" },
  "certificates.marriage.fieldBrideResidence": { en: "Residence at Marriage (Bride)", ta: "திருமணத்தின் போது வசிப்பிடம் (மணமகள்)" },
  "certificates.marriage.fieldGroomFatherName": { en: "Father's Name & Surname (Bridegroom)", ta: "தந்தையின் பெயர் & குடும்பப்பெயர் (மணமகன்)" },
  "certificates.marriage.fieldBrideFatherName": { en: "Father's Name & Surname (Bride)", ta: "தந்தையின் பெயர் & குடும்பப்பெயர் (மணமகள்)" },
  "certificates.marriage.fieldBanns": { en: "By Banns or Licence", ta: "முன்அறிவிப்பு அல்லது உரிமம் மூலம்" },
  "certificates.marriage.fieldImpediments": { en: "Can. Impediments Dispensed", ta: "விலக்கப்பட்ட தடைகள்" },
  "certificates.marriage.fieldWitness1": { en: "Witness 1", ta: "சாட்சி 1" },
  "certificates.marriage.fieldWitness2": { en: "Witness 2", ta: "சாட்சி 2" },
  "certificates.death.fieldAge": { en: "Age", ta: "வயது" },
  "certificates.death.fieldPlace": { en: "Place", ta: "இடம்" },
  "certificates.death.fieldProfession": { en: "Profession", ta: "தொழில்" },
  "certificates.death.fieldParents": { en: "Parents", ta: "பெற்றோர்" },
  "certificates.death.fieldDateOfDeath": { en: "Date of Death", ta: "இறந்த தேதி" },
  "certificates.death.fieldPlaceOfDeath": { en: "Place of Death", ta: "இறந்த இடம்" },
  "certificates.death.fieldCause": { en: "Cause", ta: "காரணம்" },
  "certificates.death.fieldConfession": { en: "C. Confession", ta: "பாவசங்கீர்த்தனம்" },
  "certificates.death.fieldViaticum": { en: "V. Viaticum", ta: "விற்றிக்கம்" },
  "certificates.death.fieldAnointing": { en: "A. Anointing", ta: "அபிஷேகம்" },
  "certificates.death.fieldDateOfBurial": { en: "Date of Burial", ta: "அடக்கம் செய்த தேதி" },
  "certificates.death.fieldPlaceOfBurial": { en: "Place of Burial", ta: "அடக்கம் செய்த இடம்" },
  "certificates.death.fieldMinister": { en: "Minister", ta: "குரு" },
  "certificates.death.fieldFamilyContact": { en: "Family Contact", ta: "குடும்ப தொடர்பு" },
  "common.name": { en: "Name", ta: "பெயர்" },
  "dashboard.colMass": { en: "Mass", ta: "திருப்பலி" },
  "massIntentions.bookedBy": { en: "Booked By", ta: "பதிவு செய்தவர்" },
  "massIntentions.phoneNumber": { en: "Phone Number", ta: "தொலைபேசி எண்" },
  "massIntentions.prayerDate": { en: "Prayer Date", ta: "ஜெப தேதி" },
  "massIntentions.colIntention": { en: "Mass Intention", ta: "திருப்பலி நோக்கம்" },
  "massIntentions.describeIntention": { en: "Describe the intention", ta: "நோக்கத்தை விவரிக்கவும்" },
  "massIntentions.offeringAmount": { en: "Offering Amount", ta: "காணிக்கை தொகை" },
  "massIntentions.paymentMethod": { en: "Payment Method", ta: "கட்டண முறை" },
  "massIntentions.remarks": { en: "Remarks", ta: "குறிப்புகள்" },
  "massIntentions.colReceiptNo": { en: "Receipt No.", ta: "ரசீது எண்." },
  "contributions.contributionType": { en: "Contribution Type", ta: "பங்களிப்பு வகை" },
  "contributions.describeType": { en: "Describe the contribution purpose", ta: "பங்களிப்பின் நோக்கத்தை விவரிக்கவும்" },
  "contributions.amount": { en: "Amount", ta: "தொகை" },
  "massIntentions.colMassDate": { en: "Mass Date", ta: "திருப்பலி தேதி" },
  "massIntentions.colOffering": { en: "Offering", ta: "காணிக்கை" },
  "certificates.baptism.colChildName": { en: "Child Name", ta: "குழந்தையின் பெயர்" },
  "massIntentions.paymentStatus": { en: "Payment Status", ta: "கட்டண நிலை" },
  // Not a UI translation key: the same wording the printed receipt uses (pdfLabels.js) for when a record was entered.
  "common.enteredDate": { en: "Entered Date", ta: "பதிவு செய்த தேதி" },
  "certificates.marriage.colGroom": { en: "Groom", ta: "மணமகன்" },
  "certificates.marriage.colBride": { en: "Bride", ta: "மணமகள்" },
  "certificates.death.colCemetery": { en: "Cemetery", ta: "கல்லறை" },
};

module.exports = { LABELS };
